sudo: required
services:
  - docker

before_install:
  - docker build -t dezirules/docker-react-test -f Dockerfile.dev .

script:
  - docker run dezirules/docker-react-test npm run test -- --coverage
